
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Jun 19 2021 22:40:08 +07 (Jun 19 2021 15:40:08 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(clk, rst, flick, lamps, stage);
  input clk, rst, flick;
  output [15:0] lamps;
  output [2:0] stage;
  wire clk, rst, flick;
  wire [15:0] lamps;
  wire [2:0] stage;
  wire [2:0] state;
  wire n_0, n_3, n_5, n_6, n_10, n_11, n_12, n_13;
  wire n_18, n_19, n_21, n_22, n_23, n_25, n_27, n_28;
  wire n_30, n_31, n_32, n_33, n_34, n_40, n_41, n_42;
  wire n_44, n_45, n_46, n_47, n_49, n_55, n_59, n_60;
  wire n_61, n_63, n_81, n_92, n_95, n_103, n_112, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_125, n_133;
  wire n_140, n_144, n_146, n_160, n_161, n_212, n_213, n_214;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_259;
  wire n_263, n_264, n_265, n_266, n_268, n_269, n_270, n_271;
  wire n_292, n_293, n_295, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312;
  DFFRHQX8 \state_reg[0] (.RN (rst), .CK (clk), .D (n_120), .Q
       (stage[0]));
  DFFRHQX8 \state_reg[1] (.RN (rst), .CK (clk), .D (n_119), .Q
       (stage[1]));
  DFFRHQX8 \state_reg[2] (.RN (rst), .CK (clk), .D (n_115), .Q
       (state[2]));
  NOR2X6 g4195__2398(.A (n_304), .B (n_269), .Y (n_118));
  NOR2X4 g4183__5107(.A (n_95), .B (n_103), .Y (n_114));
  DFFRHQX1 \led_reg[12] (.RN (rst), .CK (clk), .D (n_301), .Q
       (lamps[12]));
  DFFRHQX1 \led_reg[2] (.RN (rst), .CK (clk), .D (n_298), .Q
       (lamps[2]));
  DFFRHQX1 \led_reg[7] (.RN (rst), .CK (clk), .D (n_310), .Q
       (lamps[7]));
  DFFRHQX1 \led_reg[11] (.RN (rst), .CK (clk), .D (n_306), .Q
       (lamps[11]));
  DFFRHQX1 \led_reg[8] (.RN (rst), .CK (clk), .D (n_309), .Q
       (lamps[8]));
  DFFRHQX8 \led_reg[9] (.RN (rst), .CK (clk), .D (n_299), .Q
       (lamps[9]));
  DFFRHQX1 \led_reg[13] (.RN (rst), .CK (clk), .D (n_311), .Q
       (lamps[13]));
  DFFRHQX1 \led_reg[0] (.RN (rst), .CK (clk), .D (n_259), .Q
       (lamps[0]));
  DFFRHQX1 \led_reg[3] (.RN (rst), .CK (clk), .D (n_300), .Q
       (lamps[3]));
  DFFRHQX8 \led_reg[5] (.RN (rst), .CK (clk), .D (n_308), .Q
       (lamps[5]));
  DFFRHQX8 \led_reg[10] (.RN (rst), .CK (clk), .D (n_307), .Q
       (lamps[10]));
  DFFRHQX8 \led_reg[4] (.RN (rst), .CK (clk), .D (n_297), .Q
       (lamps[4]));
  OAI21X4 g4236__8428(.A0 (stage[2]), .A1 (n_160), .B0 (n_63), .Y
       (n_103));
  NOR2X4 g4211__5526(.A (n_19), .B (n_60), .Y (n_95));
  NAND3X4 g4220__3680(.A (lamps[9]), .B (n_292), .C (n_265), .Y (n_92));
  DFFRHQX1 \led_reg[15] (.RN (rst), .CK (clk), .D (n_302), .Q
       (lamps[15]));
  NAND2X4 g4246__2346(.A (n_30), .B (n_49), .Y (n_63));
  NOR2X4 g4217__7410(.A (n_27), .B (n_47), .Y (n_60));
  AOI221X2 g4218__6417(.A0 (lamps[0]), .A1 (stage[0]), .B0 (lamps[1]),
       .B1 (n_266), .C0 (n_41), .Y (n_59));
  NOR2X4 g4239__5526(.A (lamps[14]), .B (n_45), .Y (n_47));
  NAND2X6 g4254__6783(.A (flick), .B (n_32), .Y (n_49));
  NAND2X4 g4249__1617(.A (lamps[5]), .B (n_25), .Y (n_42));
  INVX1 g4247(.A (n_40), .Y (n_41));
  CLKAND2X12 g4255__2802(.A (n_125), .B (n_140), .Y (n_81));
  NOR2X4 g4261__5122(.A (n_21), .B (n_12), .Y (n_34));
  NOR2X2 g4262__8246(.A (n_133), .B (n_18), .Y (n_33));
  CLKINVX4 g4277(.A (n_31), .Y (n_32));
  CLKAND2X3 g4250__7098(.A (n_28), .B (n_292), .Y (n_30));
  AOI21X4 g4263__6131(.A0 (lamps[10]), .A1 (n_13), .B0 (n_28), .Y
       (n_45));
  NAND2X4 g4252__1881(.A (flick), .B (n_27), .Y (n_40));
  CLKINVX4 g4267(.A (n_23), .Y (n_44));
  NAND2X2 g4272__4733(.A (state[2]), .B (n_3), .Y (n_22));
  NAND2X4 g4270__6161(.A (stage[0]), .B (n_133), .Y (n_21));
  OR2X1 g4268__9315(.A (lamps[4]), .B (n_125), .Y (n_19));
  NAND2X4 g4273__9945(.A (stage[0]), .B (n_0), .Y (n_18));
  NAND2X6 g4275__2883(.A (stage[1]), .B (n_125), .Y (n_23));
  NAND2X2 g4283__1666(.A (lamps[4]), .B (n_13), .Y (n_12));
  NOR2X2 g4282__7410(.A (lamps[6]), .B (stage[1]), .Y (n_10));
  NAND2X8 g4284__6417(.A (lamps[9]), .B (n_144), .Y (n_25));
  NAND2X8 g4285__5477(.A (lamps[4]), .B (n_146), .Y (n_31));
  AND2X1 g4271__2398(.A (lamps[14]), .B (stage[0]), .Y (n_6));
  NOR2X8 g4274__5107(.A (stage[1]), .B (state[2]), .Y (n_27));
  NAND2X2 g4280__4319(.A (lamps[5]), .B (lamps[4]), .Y (n_5));
  BUFX2 g4300(.A (lamps[6]), .Y (n_61));
  INVX2 g4293(.A (lamps[9]), .Y (n_28));
  CLKINVX8 g4308(.A (stage[1]), .Y (n_13));
  AOI21X4 g4330__5526(.A0 (n_22), .A1 (n_44), .B0 (n_34), .Y (n_55));
  NAND2X4 g4334__6783(.A (n_118), .B (n_116), .Y (n_119));
  AOI21X4 g4336__3680(.A0 (n_125), .A1 (n_264), .B0 (n_312), .Y
       (n_117));
  NAND2X4 g4340__1617(.A (n_117), .B (n_114), .Y (n_120));
  NAND2X8 g4342__2802(.A (n_6), .B (n_112), .Y (n_116));
  OAI2BB1X2 g4366__6161(.A0N (stage[2]), .A1N (n_161), .B0 (n_92), .Y
       (n_115));
  CLKINVX8 fopt4367(.A (stage[0]), .Y (n_125));
  CLKINVX6 fopt4374(.A (n_133), .Y (stage[2]));
  CLKINVX4 fopt4375(.A (state[2]), .Y (n_133));
  CLKINVX4 fopt4381(.A (n_27), .Y (n_140));
  CLKINVX8 fopt4384(.A (lamps[10]), .Y (n_144));
  CLKINVX8 fopt4385(.A (lamps[5]), .Y (n_146));
  NAND2X4 g4410__6260(.A (n_144), .B (flick), .Y (n_11));
  NAND2BX4 g4413__8428(.AN (lamps[1]), .B (n_44), .Y (n_160));
  CLKAND2X6 g4264__4461(.A (n_212), .B (n_213), .Y (n_214));
  NAND2X4 g4269__4463(.A (stage[1]), .B (state[2]), .Y (n_213));
  AOI22X4 g4227__4465(.A0 (lamps[3]), .A1 (n_81), .B0 (lamps[1]), .B1
       (n_214), .Y (n_217));
  AOI22X4 g4229__4466(.A0 (lamps[12]), .A1 (n_81), .B0 (lamps[10]), .B1
       (n_214), .Y (n_218));
  AOI22X4 g4226__4467(.A0 (lamps[2]), .A1 (n_81), .B0 (lamps[0]), .B1
       (n_214), .Y (n_219));
  AOI22X4 g4221__4468(.A0 (n_61), .A1 (n_81), .B0 (lamps[4]), .B1
       (n_214), .Y (n_220));
  AOI22X4 g4224__4469(.A0 (lamps[9]), .A1 (n_81), .B0 (lamps[7]), .B1
       (n_214), .Y (n_221));
  AOI22X4 g4222__4470(.A0 (lamps[7]), .A1 (n_81), .B0 (lamps[5]), .B1
       (n_214), .Y (n_222));
  AOI22X4 g4232__4471(.A0 (lamps[14]), .A1 (n_81), .B0 (lamps[12]), .B1
       (n_223), .Y (n_224));
  CLKAND2X6 g4264__7482_dup(.A (n_212), .B (n_213), .Y (n_223));
  AOI22X4 g4230__4472(.A0 (lamps[13]), .A1 (n_81), .B0 (lamps[11]), .B1
       (n_223), .Y (n_225));
  AOI22X4 g4228__4473(.A0 (lamps[11]), .A1 (n_81), .B0 (lamps[9]), .B1
       (n_223), .Y (n_226));
  AOI22X4 g4233__4474(.A0 (lamps[15]), .A1 (n_81), .B0 (lamps[13]), .B1
       (n_223), .Y (n_227));
  AOI22X4 g4223__4475(.A0 (lamps[8]), .A1 (n_81), .B0 (n_61), .B1
       (n_223), .Y (n_228));
  AOI22X4 g4235__4476(.A0 (lamps[5]), .A1 (n_81), .B0 (lamps[3]), .B1
       (n_223), .Y (n_229));
  AOI22X4 g4225__4477(.A0 (lamps[4]), .A1 (n_81), .B0 (lamps[2]), .B1
       (n_223), .Y (n_230));
  AOI22X4 g4231__4478(.A0 (lamps[10]), .A1 (n_81), .B0 (lamps[8]), .B1
       (n_223), .Y (n_231));
  DFFRX2 \led_reg[14] (.RN (rst), .CK (clk), .D (n_305), .Q
       (lamps[14]), .QN (n_0));
  DFFRX2 \led_reg[1] (.RN (rst), .CK (clk), .D (n_295), .Q (lamps[1]),
       .QN (n_3));
  DFFRHQX1 \led_reg[6] (.RN (rst), .CK (clk), .D (n_296), .Q
       (lamps[6]));
  NAND2BX2 g4510(.AN (n_214), .B (n_59), .Y (n_259));
  OAI2BB1X4 g4514(.A0N (flick), .A1N (n_42), .B0 (n_33), .Y (n_263));
  OAI2BB1X4 g4515(.A0N (stage[2]), .A1N (n_10), .B0 (n_40), .Y (n_264));
  OAI2BB1X2 g4516(.A0N (lamps[10]), .A1N (n_31), .B0 (flick), .Y
       (n_265));
  OAI2BB1X2 g4517(.A0N (n_13), .A1N (state[2]), .B0 (n_23), .Y (n_266));
  CLKAND2X3 g4519(.A (n_268), .B (n_292), .Y (n_269));
  NAND3X4 g3(.A (lamps[9]), .B (n_11), .C (n_49), .Y (n_268));
  OAI2BB1X4 g4520(.A0N (n_270), .A1N (flick), .B0 (stage[2]), .Y
       (n_271));
  NAND2BX4 g4521(.AN (lamps[4]), .B (n_25), .Y (n_270));
  NAND2BX1 g4253_0__4523(.AN (lamps[1]), .B (n_44), .Y (n_161));
  NAND2X4 g4392__4525(.A (n_271), .B (n_46), .Y (n_112));
  OR2X6 g4406__4529(.A (n_5), .B (n_45), .Y (n_46));
  INVX3 fopt4531(.A (n_125), .Y (n_212));
  CLKAND2X12 g4286__4551(.A (stage[1]), .B (stage[0]), .Y (n_292));
  CLKAND2X6 g4553(.A (state[2]), .B (n_292), .Y (n_293));
  OAI2BB1X2 g4379__4554(.A0N (n_293), .A1N (lamps[1]), .B0 (n_219), .Y
       (n_295));
  OAI2BB1X2 g4404__4555(.A0N (n_61), .A1N (n_293), .B0 (n_222), .Y
       (n_296));
  OAI2BB1X2 g4398__4556(.A0N (lamps[4]), .A1N (n_293), .B0 (n_229), .Y
       (n_297));
  OAI2BB1X2 g4360__4557(.A0N (lamps[2]), .A1N (n_293), .B0 (n_217), .Y
       (n_298));
  OAI2BB1X2 g4396__4558(.A0N (lamps[9]), .A1N (n_293), .B0 (n_231), .Y
       (n_299));
  OAI2BB1X2 g4358__4559(.A0N (lamps[3]), .A1N (n_293), .B0 (n_230), .Y
       (n_300));
  OAI2BB1X2 g4350__4560(.A0N (lamps[12]), .A1N (n_293), .B0 (n_225), .Y
       (n_301));
  AO22X1 g4561(.A0 (lamps[15]), .A1 (n_293), .B0 (lamps[14]), .B1
       (n_214), .Y (n_302));
  NAND2BX4 g4562(.AN (n_303), .B (n_55), .Y (n_304));
  CLKAND2X6 g2_dup(.A (state[2]), .B (n_292), .Y (n_303));
  OAI2BB1X4 g4364__4563(.A0N (lamps[14]), .A1N (n_303), .B0 (n_227), .Y
       (n_305));
  OAI2BB1X2 g4348__4564(.A0N (lamps[11]), .A1N (n_303), .B0 (n_218), .Y
       (n_306));
  OAI2BB1X2 g4402__4565(.A0N (lamps[10]), .A1N (n_303), .B0 (n_226), .Y
       (n_307));
  OAI2BB1X2 g4400__4566(.A0N (lamps[5]), .A1N (n_303), .B0 (n_220), .Y
       (n_308));
  OAI2BB1X2 g4354__4567(.A0N (lamps[8]), .A1N (n_303), .B0 (n_221), .Y
       (n_309));
  OAI2BB1X2 g4352__4568(.A0N (lamps[7]), .A1N (n_303), .B0 (n_228), .Y
       (n_310));
  OAI2BB1X2 g4356__4569(.A0N (lamps[13]), .A1N (n_303), .B0 (n_224), .Y
       (n_311));
  NAND2BX4 g2(.AN (n_293), .B (n_263), .Y (n_312));
endmodule

